server:
  port: 8088

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: nabilcode
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/




